index:
    path: /
    controller: App\Controller\HomeController::index

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

article_photo:
    path: /articles/photos/{filename}
    controller: App\Controller\ArticleController::getArticlePhoto

api_refresh_token:
    path: /api/token/refresh
